export const TODO_FETCH_START = 'TODO_FETCH_START';
export const TODO_FETCH_SUCCESS = 'TODO_FETCH_SUCCESS';
export const TODO_FETCH_FAIL = 'TODO_FETCH_FAIL';

export const TODO_ADD_START = 'TODO_ADD_START';
export const TODO_ADD_SUCCESS = 'TODO_ADD_SUCCESS';
export const TODO_ADD_FAIL = 'TODO_ADD_FAIL';

export const TODO_NAME_CHANGED = 'TODO_NAME_CHANGED';

export const TODO_TOGGLE_SUCCESS = 'TODO_TOGGLE_SUCCESS';
export const TODO_TOGGLE_FAIL = 'TODO_TOGGLE_FAIL';

export const TODO_DELETE_SUCCESS = 'TODO_DELETE_SUCCESS';
export const TODO_DELETE_FAIL = 'TODO_DELETE_FAIL';

export const TODO_DELETE_COMPLETED_START = 'TODO_DELETE_COMPLETED_START';
export const TODO_DELETE_COMPLETED_SUCCESS = 'TODO_DELETE_COMPLETED_SUCCESS';
export const TODO_DELETE_COMPLETED_FAIL = 'TODO_DELETE_COMPLETED_FAIL';

export const TODO_TOGGLE_MASS_START = 'TODO_TOGGLE_MASS_START';
export const TODO_TOGGLE_MASS_SUCCESS = 'TODO_TOGGLE_MASS_SUCCESS';
export const TODO_TOGGLE_MASS_FAIL = 'TODO_TOGGLE_MASS_FAIL';

export const TODO_FILTER_ACTION = 'TODO_FILTER_ACTION';
export const filterActions = {
    ALL: 'ALL',
    ACTIVE: 'ACTIVE',
    COMPLETED: 'COMPLETED'
};

export const TODO_EDIT_START = 'TODO_EDIT_START';
export const TODO_EDIT = 'TODO_EDIT';
export const TODO_EDIT_CANCEL = 'TODO_EDIT_CANCEL';
export const TODO_EDIT_UPDATE_SUCCESS = 'TODO_EDIT_UPDATE_SUCCESS';
export const TODO_EDIT_UPDATE_FAIL = 'TODO_EDIT_UPDATE_FAIL';