export const TODO_ADD_SUCCESS = 'TODO_ADD_SUCCESS';
export const TODO_ADD_FAIL = 'TODO_ADD_FAIL';

export const TODO_NAME_CHANGED = 'TODO_NAME_CHANGED';

export const TODO_TOGGLE_SUCCESS = 'TODO_TOGGLE_SUCCESS';
export const TODO_TOGGLE_FAIL = 'TODO_TOGGLE_FAIL';

export const TODO_DELETE_SUCCESS = 'TODO_DELETE_SUCCESS';
export const TODO_DELETE_FAIL = 'TODO_DELETE_FAIL';
